name: linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - name: Checkout libnunchuk
        working-directory: ${{runner.workspace}}
        run: |
          git clone https://github.com/nunchuk-io/libnunchuk --depth 1
          cd libnunchuk
          git submodule update --depth 1 --init --recursive
        
      - name: Install packages
        run: sudo apt install libevent-dev libssl-dev libdb-dev libdb++-dev build-essential libtool autotools-dev automake pkg-config bsdmainutils mesa-common-dev libglu1-mesa-dev zip

      - name: Cache Boost
        uses: actions/cache@v2
        id: cache-boost
        with:
          path: ${{runner.workspace}}/boost_1_73_0
          key: linux-boost-1.73.0

      - name: Install Boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: |
          wget -q "https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2"
          tar --bzip2 -xf ./boost_1_73_0.tar.bz2
          cd boost_1_73_0
          ./bootstrap.sh --prefix=${{runner.workspace}}/boost_1_73_0
          ./b2 install
 
      - name: Cache libnunchuk contrib
        uses: actions/cache@v2
        id: cache-contrib
        with:
          path: ${{runner.workspace}}/libnunchuk/contrib
          key: linux-543693b92b954d186cb466a2f14b480f3bcf8c0b

      - name: Build Bitcoin Core
        if: steps.cache-contrib.outputs.cache-hit != 'true'
        working-directory: ${{runner.workspace}}/libnunchuk/contrib/bitcoin
        run: |
          ./autogen.sh
          ./configure --without-gui --disable-zmq --with-miniupnpc=no --with-incompatible-bdb --disable-bench --disable-tests --with-boost=${{runner.workspace}}/boost_1_73_0
          make -j8

      - name: Build SqlCipher
        if: steps.cache-contrib.outputs.cache-hit != 'true'
        working-directory: ${{runner.workspace}}/libnunchuk/contrib/sqlcipher
        run: |
          ./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" LDFLAGS="-lcrypto"
          make -j8

      - name: Build libnunchuk
        working-directory: ${{runner.workspace}}
        shell: bash
        run: |
          cmake -E make_directory ${{runner.workspace}}/build
          cd build
          cmake ${{runner.workspace}}/libnunchuk -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=${{runner.workspace}}/boost_1_73_0 -DUR__DISABLE_TESTS=ON
          cmake --build . --config Release -j8
